# Copyright (C) 2018 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/universal8890-common/setup-makefiles.sh

PRODUCT_COPY_FILES += \
  vendor/samsung/universal8890-common/apps/RootPA/lib/arm/libcommonpawrapper.so:system/app/RootPA/lib/arm/libcommonpawrapper.so \
  vendor/samsung/universal8890-common/proprietary/lib/hw/gralloc.exynos5.so:system/lib/hw/gralloc.exynos5.so \
  vendor/samsung/universal8890-common/proprietary/lib/libExynosOMX_Core.so:system/lib/libExynosOMX_Core.so \
  vendor/samsung/universal8890-common/proprietary/lib/libExynosOMX_Resourcemanager.so:system/lib/libExynosOMX_Resourcemanager.so \
  vendor/samsung/universal8890-common/proprietary/lib/libcsc.so:system/lib/libcsc.so \
  vendor/samsung/universal8890-common/proprietary/lib/libexynosgscaler.so:system/lib/libexynosgscaler.so \
  vendor/samsung/universal8890-common/proprietary/lib/libexynosscaler.so:system/lib/libexynosscaler.so \
  vendor/samsung/universal8890-common/proprietary/lib/libexynosv4l2.so:system/lib/libexynosv4l2.so \
  vendor/samsung/universal8890-common/proprietary/lib/libfloatingfeature.so:system/lib/libfloatingfeature.so \
  vendor/samsung/universal8890-common/proprietary/lib/libhwjpeg.so:system/lib/libhwjpeg.so \
  vendor/samsung/universal8890-common/proprietary/lib/libsecnativefeature.so:system/lib/libsecnativefeature.so \
  vendor/samsung/universal8890-common/proprietary/lib/libsensorlistener.so:system/lib/libsensorlistener.so \
  vendor/samsung/universal8890-common/proprietary/lib/libuniplugin.so:system/lib/libuniplugin.so \
  vendor/samsung/universal8890-common/proprietary/lib/omx/libOMX.Exynos.AVC.Decoder.so:system/lib/omx/libOMX.Exynos.AVC.Decoder.so \
  vendor/samsung/universal8890-common/proprietary/lib/omx/libOMX.Exynos.AVC.Encoder.so:system/lib/omx/libOMX.Exynos.AVC.Encoder.so \
  vendor/samsung/universal8890-common/proprietary/lib/omx/libOMX.Exynos.MPEG4.Decoder.so:system/lib/omx/libOMX.Exynos.MPEG4.Decoder.so \
  vendor/samsung/universal8890-common/proprietary/lib/omx/libOMX.Exynos.MPEG4.Encoder.so:system/lib/omx/libOMX.Exynos.MPEG4.Encoder.so \
  vendor/samsung/universal8890-common/proprietary/lib/omx/libOMX.Exynos.VP8.Decoder.so:system/lib/omx/libOMX.Exynos.VP8.Decoder.so \
  vendor/samsung/universal8890-common/proprietary/lib/omx/libOMX.Exynos.VP8.Encoder.so:system/lib/omx/libOMX.Exynos.VP8.Encoder.so \
  vendor/samsung/universal8890-common/proprietary/lib/omx/libOMX.Exynos.WMV.Decoder.so:system/lib/omx/libOMX.Exynos.WMV.Decoder.so \
  vendor/samsung/universal8890-common/proprietary/lib/omx/libOMX.Exynos.MPEG2.Decoder.so:system/lib/omx/libOMX.Exynos.MPEG2.Decoder.so \
  vendor/samsung/universal8890-common/proprietary/lib/omx/libOMX.Exynos.HEVC.Decoder.so:system/lib/omx/libOMX.Exynos.HEVC.Decoder.so \
  vendor/samsung/universal8890-common/proprietary/lib/omx/libOMX.Exynos.HEVC.Encoder.so:system/lib/omx/libOMX.Exynos.HEVC.Encoder.so \
  vendor/samsung/universal8890-common/proprietary/lib/omx/libOMX.Exynos.VP9.Decoder.so:system/lib/omx/libOMX.Exynos.VP9.Decoder.so \
  vendor/samsung/universal8890-common/proprietary/lib/omx/libOMX.Exynos.VP9.Encoder.so:system/lib/omx/libOMX.Exynos.VP9.Encoder.so \
  vendor/samsung/universal8890-common/proprietary/lib/libcommonpawrapper.so:system/lib/libcommonpawrapper.so \
  vendor/samsung/universal8890-common/proprietary/lib/libcurl.so:system/lib/libcurl.so \
  vendor/samsung/universal8890-common/proprietary/lib/libexynosdisplay.so:system/lib/libexynosdisplay.so \
  vendor/samsung/universal8890-common/proprietary/lib/libexynosutils.so:system/lib/libexynosutils.so \
  vendor/samsung/universal8890-common/proprietary/lib/libfimg.so:system/lib/libfimg.so \
  vendor/samsung/universal8890-common/proprietary/lib/libhdmi.so:system/lib/libhdmi.so \
  vendor/samsung/universal8890-common/proprietary/lib/libhwcutils.so:system/lib/libhwcutils.so \
  vendor/samsung/universal8890-common/proprietary/lib/libion_exynos.so:system/lib/libion_exynos.so \
  vendor/samsung/universal8890-common/proprietary/lib/libmpp.so:system/lib/libmpp.so \
  vendor/samsung/universal8890-common/proprietary/lib/libstagefrighthw.so:system/ lib/libstagefrighthw.so \
  vendor/samsung/universal8890-common/proprietary/lib/libprotobuf-cpp-N.so:system/lib/libprotobuf-cpp-N.so \
  vendor/samsung/universal8890-common/proprietary/vendor/lib/libsec-ril.so:system/vendor/lib/libsec-ril.so \
  vendor/samsung/universal8890-common/proprietary/vendor/lib/libsec-ril-dsds.so:system/vendor/lib/libsec-ril-dsds.so \
  vendor/samsung/universal8890-common/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \
  vendor/samsung/universal8890-common/proprietary/vendor/lib/egl/libGLES_mali.so:system/vendor/lib/egl/libGLES_mali.so \
  vendor/samsung/universal8890-common/proprietary/vendor/lib64/egl/libGLES_mali.so:system/vendor/lib64/egl/libGLES_mali.so \
  vendor/samsung/universal8890-common/proprietary/vendor/lib64/hw/gps.default.so:system/vendor/lib64/hw/gps.default.so \
  vendor/samsung/universal8890-common/proprietary/vendor/lib64/hw/nfc_nci.default.so:system/vendor/lib64/hw/nfc_nci.default.so \
  vendor/samsung/universal8890-common/proprietary/vendor/lib64/hw/vendor.samsung.hardware.gnss@1.0-impl.so:system/vendor/lib64/hw/vendor.samsung.hardware.gnss@1.0-impl.so \
  vendor/samsung/universal8890-common/proprietary/vendor/lib64/hw/vendor.samsung.hardware.nfc@1.0-impl.so:system/vendor/lib64/hw/vendor.samsung.hardware.nfc@1.0-impl.so \
  vendor/samsung/universal8890-common/proprietary/vendor/lib64/libsec-ril-dsds.so:system/vendor/lib64/libsec-ril-dsds.so \
  vendor/samsung/universal8890-common/proprietary/vendor/lib64/libsec-ril.so:system/vendor/lib64/libsec-ril.so:system \
  vendor/samsung/universal8890-common/proprietary/lib64/hw/gralloc.exynos5.so:system/lib64/hw/gralloc.exynos5.so \
  vendor/samsung/universal8890-common/proprietary/lib64/omx/libOMX.Exynos.MPEG2.Decoder.so:system/lib64/omx/libOMX.Exynos.MPEG2.Decoder.so \
  vendor/samsung/universal8890-common/proprietary/lib64/omx/libOMX.Exynos.AVC.Decoder.so:system/lib64/omx/libOMX.Exynos.AVC.Decoder.so \
  vendor/samsung/universal8890-common/proprietary/lib64/omx/libOMX.Exynos.AVC.Encoder.so:system/lib64/omx/libOMX.Exynos.AVC.Encoder.so \
  vendor/samsung/universal8890-common/proprietary/lib64/omx/libOMX.Exynos.HEVC.Decoder.so:system/lib64/omx/libOMX.Exynos.HEVC.Decoder.so \
  vendor/samsung/universal8890-common/proprietary/lib64/omx/libOMX.Exynos.HEVC.Encoder.so:system/lib64/omx/libOMX.Exynos.HEVC.Encoder.so \
  vendor/samsung/universal8890-common/proprietary/lib64/omx/libOMX.Exynos.MPEG4.Decoder.so:system/lib64/omx/libOMX.Exynos.MPEG4.Decoder.so \
  vendor/samsung/universal8890-common/proprietary/lib64/omx/libOMX.Exynos.MPEG4.Encoder.so:system/lib64/omx/libOMX.Exynos.MPEG4.Encoder.so \
  vendor/samsung/universal8890-common/proprietary/lib64/omx/libOMX.Exynos.VP8.Decoder.so:system/lib64/omx/libOMX.Exynos.VP8.Decoder.so \
  vendor/samsung/universal8890-common/proprietary/lib64/omx/libOMX.Exynos.VP8.Encoder.so:system/lib64/omx/libOMX.Exynos.VP8.Encoder.so \
  vendor/samsung/universal8890-common/proprietary/lib64/omx/libOMX.Exynos.VP9.Decoder.so:system/lib64/omx/libOMX.Exynos.VP9.Decoder.so \
  vendor/samsung/universal8890-common/proprietary/lib64/omx/libOMX.Exynos.VP9.Encoder.so:system/lib64/omx/libOMX.Exynos.VP9.Encoder.so \
  vendor/samsung/universal8890-common/proprietary/lib64/omx/libOMX.Exynos.WMV.Decoder.so:system/lib64/omx/libOMX.Exynos.WMV.Decoder.so \
  vendor/samsung/universal8890-common/proprietary/lib64/libexynosdisplay.so:system/lib64/libexynosdisplay.so \
  vendor/samsung/universal8890-common/proprietary/lib64/libexynosutils.so:system/lib64/libexynosutils.so \
  vendor/samsung/universal8890-common/proprietary/lib64/libexynosv4l2.so:system/lib64/libexynosv4l2.so \
  vendor/samsung/universal8890-common/proprietary/lib64/libfimg.so:system/lib64/libfimg.so \
  vendor/samsung/universal8890-common/proprietary/lib64/libhdmi.so:system/lib64/libhdmi.so \
  vendor/samsung/universal8890-common/proprietary/lib64/libhwcutils.so:system/lib64/libhwcutils.so \
  vendor/samsung/universal8890-common/proprietary/lib64/libion_exynos.so:system/lib64/libion_exynos.so \
  vendor/samsung/universal8890-common/proprietary/lib64/libmpp.so:system/lib64/libmpp.so \
  vendor/samsung/universal8890-common/proprietary/lib64/libcsc.so:system/lib64/libcsc.so \
  vendor/samsung/universal8890-common/proprietary/lib64/libexynosgscaler.so:system/lib64/libexynosgscaler.so \
  vendor/samsung/universal8890-common/proprietary/lib64/libprotobuf-cpp-N.so:system/lib64/libprotobuf-cpp-N.so \
  vendor/samsung/universal8890-common/proprietary/lib64/libhwjpeg.so:system/lib64/libhwjpeg.so \
  vendor/samsung/universal8890-common/proprietary/lib64/libExynosOMX_Core.so:system/lib64/libExynosOMX_Core.so \
  vendor/samsung/universal8890-common/proprietary/lib64/libExynosOMX_Resourcemanager.so:system/lib64/libExynosOMX_Resourcemanager.so \
  vendor/samsung/universal8890-common/proprietary/lib64/libuniplugin.so:system/lib64/libuniplugin.so \
  vendor/samsung/universal8890-common/proprietary/lib64/libstagefrighthw.so:system/lib64/libstagefrighthw.so \
  vendor/samsung/universal8890-common/proprietary/lib64/libsensorlistener.so:system/lib64/libsensorlistener.so \
  vendor/samsung/universal8890-common/proprietary/lib64/libsecnativefeature.so:system/lib64/libsecnativefeature.so \
  vendor/samsung/universal8890-common/proprietary/lib64/libexynosscaler.so:system/lib64/libexynosscaler.so \
  vendor/samsung/universal8890-common/proprietary/lib64/libfloatingfeature.so:system/lib64/libfloatingfeature.so
